### ISSUE TITLE
Outdated "DocBook V5.x" page: Missing official 5.1 schema

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#87] opened 2017-03-30 12:36 UTC
The "DocBook V5.x" page under http://docbook.org/schemas/5x.html seems to be outdated.

The last version of 5.1 points to the candidate releases (from 2014!). However, 5.1 is already a published standard on OASIS, see https://www.oasis-open.org/standards#docbook-5.1

Please update the page accordingly and also publish the schemas on www.docbook.org.

**Comment by kosek** [comment] 2017-03-30 18:33
Please report issues on docbook.org on its respective issue tracker in docbook/docbook.org repository.

Actually this is duplicate of https://github.com/docbook/docbook.org/issues/8

**Closed** 2017-03-30 18:33 UTC
