### ISSUE TITLE
Epigraphs should allow poetry in Publishers schema

### ISSUE THREAD

**Issue by shudson310** [docbook/docbook#84] opened 2017-03-15 18:23 UTC
Poetry is a common component of epigraphs in trade and academic publishing. It seems entirely consistent that DocBook publishers should allow this too.

ACCEPTED: allow linegroup and poetry in epigraph per Publishers SC meeting on 15 Feb 2012.

**Comment by robotsnowfall** [comment] 2020-01-01 18:14
Looks like this change is reflected in the repo since https://github.com/docbook/docbook/commit/72f5acc92246eeb228552dd7a449fade1fdc4ac0. Are the issues in the project tracking changes in the code or things awaiting some additional steps in the standards process?

**Comment by kosek** [comment] 2021-03-15 20:01
> Looks like this change is reflected in the repo since [72f5acc](https://github.com/docbook/docbook/commit/72f5acc92246eeb228552dd7a449fade1fdc4ac0). Are the issues in the project tracking changes in the code or things awaiting some additional steps in the standards process?

Beta releases are currently done irregularly. But I expect that new beta release will be made shortly after batch of Publishers related schema is finished.

There was issue in build system (#188) that prevented epigraph change to appear in the final compiled schema.

**Comment by kosek** [comment] 2021-03-15 20:03
> Poetry is a common component of epigraphs in trade and academic publishing. It seems entirely consistent that DocBook publishers should allow this too.
> 
> ACCEPTED: allow linegroup and poetry in epigraph per Publishers SC meeting on 15 Feb 2012.

I see it's quite old decision. But shouldn't be content model of epigraph aligned with poem/drama/... and use something like

````
   db.epigraph =
      element epigraph {
         db.epigraph.attlist,
         db.epigraph.info,
         db.attribution?,
         (db.para.blocks | db.literallayout | db.extension.blocks | db.linegroup | db.line)+
      }
````

Ie. add linegroup and line elements but not poetry element. Is that what was intended back in 2012?

**Comment by kosek** [comment] 2021-03-21 13:29
Closing after offline clarification with @shudson310 
Poetry is included via db.extension.blocks pattern

**Closed by kosek** 2021-03-21 13:29 UTC
Labels: Pubv5.2, publishers

**Comment by toraritte** [comment] 2021-11-14 03:16
> Poetry is included via `db.extension.blocks` pattern

Does this mean that elements that were present in DocBook v5.1 (e.g., [`poetry`](https://tdg.docbook.org/tdg/publishers/5.1/poetry.html), [`drama`](https://tdg.docbook.org/tdg/publishers/5.1/drama.html), [`dialogue`](https://tdg.docbook.org/tdg/publishers/5.1/dialogue.html), [`line`](https://tdg.docbook.org/tdg/publishers/5.1/line.html)), but removed from v5.2 (see [reference](https://tdg.docbook.org/tdg/5.2/part2.html)), can be re-added via the methods described in [Chapter 5. Customizing DocBook](https://tdg.docbook.org/tdg/5.2/ch05.html)?
